In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
import keras
from tensorflow.keras.layers import *

Using TensorFlow backend.


In [5]:
prep_male = pd.read_excel('../datasets/prep_male.xlsx', index_col=0)
prep_female = pd.read_excel('../datasets/prep_female.xlsx', index_col=0)

In [6]:
data = pd.concat([prep_male, prep_female], axis= 'rows')
data.columns

Index(['성별', '생년', '검진년도', '검진 시 연령', '키', '체중', '허리둘레', 'BMI', '시력(좌)',
       '시력(우)', '청력(좌)', '청력(우)', '수축기혈압', '이완기혈압', '요단백', '헤모글로빈', '공복혈당',
       '총콜레스테롤', 'HDL', '중성지방', 'LDL', '혈청크레아티닌', '신사구체여과율', 'AST', 'ALT',
       'GTP', '폐결핵흉부질환'],
      dtype='object')

In [7]:
data.to_csv('../datasets/prep_total.csv')

In [9]:
data = pd.read_csv('../datasets/prep_total.csv', index_col=0)
data.reset_index(inplace= True)
data.rename(columns={'고유값':'일련번호'}, inplace=True)
data

일련번호 성별    생년  검진년도  검진 시 연령      키    체중  허리둘레   BMI  시력(좌)  ...  \
0      M0  M  1977  2010       34  174.0  64.0  72.0  21.1    1.2  ...   
1      M0  M  1977  2011       35  175.0  68.0  79.0  22.2    1.0  ...   
2      M0  M  1977  2012       36  175.0  68.0  76.0  22.2    0.7  ...   
3      M0  M  1977  2013       37  175.0  81.0  92.0  26.4    0.7  ...   
4      M0  M  1977  2014       38  175.0  86.0  96.0  28.1    0.6  ...   
...   ... ..   ...   ...      ...    ...   ...   ...   ...    ...  ...   
1063  F30  F  1971  2015       45  154.0  54.0  75.0  22.8    0.9  ...   
1064  F30  F  1971  2016       46  154.0  55.0  70.0  23.2    1.0  ...   
1065  F30  F  1971  2017       47  153.6  54.2  69.0  23.0    1.2  ...   
1066  F30  F  1971  2018       48  153.2  54.7  75.8  23.3    0.9  ...   
1067  F30  F  1971  2019       49  153.6  53.7  75.5  22.8    1.2  ...   

      총콜레스테롤   HDL   중성지방    LDL  혈청크레아티닌 신사구체여과율  AST   ALT  GTP  폐결핵흉부질환  
0      194.0  47.0   84.0  130.0      1.2     171   18  13.0   12       정상  
1      182.0  52.0   90.0  111.0      1.2     169   18  11.0   16       정상  
2      176.0  38.0  188.0  100.0      1.1      80   21  15.0   17       정상  
3      203.0  42.0  135.0  134.0      1.1      80   16  17.0   18       정상  
4      205.0  45.0  141.0  132.0      0.9     100   19  28.0   23       정상  
...      ...   ...    ...    ...      ...     ...  ...   ...  ...      ...  
1063   213.0  64.0   76.0  133.0      0.9      72   21   9.0   16       정상  
1064   225.0  61.0   73.0  149.0      0.9      72   20  13.0   14       정상  
1065   197.0  60.0   86.0  120.0      0.9      71   18  10.0   11       정상  
1066     NaN   NaN    NaN    NaN      0.9      71   19  13.0   13       정상  
1067   227.0  61.0   90.0  148.0      0.9      71   21  15.0   18       정상  

[1068 rows x 28 columns]

In [11]:
data = data[['검진 시 연령','키','체중', '허리둘레', 'BMI','수축기혈압', '이완기혈압']]

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
# MinMaxScaling 실행
minmaxscaler = MinMaxScaler()
scaled_data = minmaxscaler.fit_transform(data[['검진 시 연령', '체중', '허리둘레', 'BMI', '수축기혈압', '이완기혈압']])
print(scaled_data[:6])
print(scaled_data.shape)

[[0.28888889 0.30327869 0.24590164 0.20725389 0.5        0.46774194]
 [0.31111111 0.3579235  0.36065574 0.2642487  0.375      0.30645161]
 [0.33333333 0.3579235  0.31147541 0.2642487  0.375      0.30645161]
 [0.35555556 0.53551913 0.57377049 0.48186528 0.55       0.4516129 ]
 [0.37777778 0.60382514 0.63934426 0.56994819 0.5875     0.51612903]
 [0.4        0.53551913 0.54098361 0.46632124 0.6        0.61290323]]
(1068, 6)


In [ ]:
sequence_X = []
sequence_Y = []
for i in range(0, len(scaled_data) - 4):
    _x = scaled_data[i : i + 4]
    _y = scaled_data[i + 4][4]
    sequence_X.append(_x)
    sequence_Y.append(_y)